del /q /s F:\MyAndroid\GameMarket\bin\classes\res
del /q /s F:\MyAndroid\GameMarket\bin\classes\classes.dex
del /q /s F:\MyAndroid\GameMarket\bin\classes
rd /q /s F:\MyAndroid\GameMarket\bin\classes
mkdir F:\MyAndroid\GameMarket\bin\classes

E:\Development\Java1.6\bin\javac -encoding UTF-8 -bootclasspath E:\Development\Android\platforms\android-8\android.jar;E:\Development\Android\tools\support\annotations.jar;F:\MyAndroid\GameMarket\libs\android-support-v13.jar;F:\MyAndroid\GameMarket\libs\dom4j-1.6.1.jar -d F:\MyAndroid\GameMarket\bin\classes F:\MyAndroid\GameMarket\src\com\apps\game\market\activity\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\adapter\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\broadcast\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\entity\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\entity\app\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\enums\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\global\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\request\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\request\app\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\request\callback\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\task\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\util\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\view\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\view\callback\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\viewholder\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\views\*.java F:\MyAndroid\GameMarket\src\com\apps\game\market\*.java F:\MyAndroid\GameMarket\gen\com\apps\game\market\R.java
call E:\Development\Android\platform-tools\dx.bat --dex --output=F:\MyAndroid\GameMarket\bin\classes.dex F:\MyAndroid\GameMarket\bin\classes E:\Development\Android\tools\support\annotations.jar F:\MyAndroid\GameMarket\libs\android-support-v13.jar F:\MyAndroid\GameMarket\libs\dom4j-1.6.1.jar
E:\Development\Android\platform-tools\aapt.exe package -f -M F:\MyAndroid\GameMarket\AndroidManifest.xml -S F:\MyAndroid\GameMarket\res -A F:\MyAndroid\GameMarket\assets -I E:\Development\Android\platforms\android-8\android.jar -F F:\MyAndroid\GameMarket\bin\res
call E:\Development\Android\tools\apkbuilder.bat F:\MyAndroid\GameMarket\bin\GameMarket_%1.apk -v -u -rf F:\MyAndroid\GameMarket\src -f F:\MyAndroid\GameMarket\bin\classes.dex -z F:\MyAndroid\GameMarket\bin\res
E:\Development\Java1.6\bin\jarsigner -keystore F:\MyAndroid\GameMarket\myandroid.keystore -storepass 12345678 -keypass 12345678 -signedjar F:\MyAndroid\GameMarket\bin\GameMarket_singed_%1.apk F:\MyAndroid\GameMarket\bin\GameMarket_%1.apk myandroid.keystore